// <auto-generated />
using System;
using IKnowCoding.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(PlatformContext))]
    [Migration("20240519191211_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Entities.User.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("UserSettingsId")
                        .HasColumnType("int")
                        .HasColumnName("user_settings_id");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "valik@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Valentyn",
                            LastName = "Riabinchak",
                            Password = "11111111",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "vasylyna@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Vasylyna",
                            LastName = "Leheta",
                            Password = "22222222",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "igor@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Igor",
                            LastName = "Zaitsev",
                            Password = "33333333",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "tom@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Tom",
                            LastName = "Bot",
                            Password = "44444444",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 5,
                            Email = "admin@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Mr. Admin",
                            LastName = "Secret Administator",
                            Password = "secretKey911#",
                            UserSettingsId = 0
                        });
                });

            modelBuilder.Entity("DAL.Models.Entities.User.UserSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("access_token");

                    b.Property<DateTime?>("AccessTokenExpireTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("access_token_expire_time");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpireTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expire_time");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsAdmin = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsAdmin = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            IsAdmin = false,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("IKnowCoding.API.Models.DTO.MainPage.FeedbackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_path");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(7795),
                            ImagePath = "",
                            Text = "Very nice",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(8236),
                            ImagePath = "",
                            Text = "Very nice",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(8237),
                            ImagePath = "",
                            Text = "Very nice",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(8237),
                            ImagePath = "",
                            Text = "Very nice",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(8238),
                            ImagePath = "",
                            Text = "Very nice",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.DTO.Main_Page.AchievementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_path");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(6809),
                            ImagePath = "",
                            Source = "site.com",
                            Text = "The best testing website",
                            Title = "Best"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(7091),
                            ImagePath = "",
                            Source = "site.com",
                            Text = "Nice site",
                            Title = "Nice"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(7092),
                            ImagePath = "",
                            Source = "site.com",
                            Text = "Strong olympiad",
                            Title = "Olimpiad"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(7092),
                            ImagePath = "",
                            Source = "site.com",
                            Text = "~70 points of 100",
                            Title = "Universities"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(7093),
                            ImagePath = "",
                            Source = "site.com",
                            Text = "All estimation is based on the Europe system",
                            Title = "European estimation"
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.AnswerVariantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRight")
                        .HasColumnType("bit")
                        .HasColumnName("is_right");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsRight = true,
                            QuestionId = 1,
                            Text = "1"
                        },
                        new
                        {
                            Id = 2,
                            IsRight = false,
                            QuestionId = 1,
                            Text = "2"
                        },
                        new
                        {
                            Id = 3,
                            IsRight = false,
                            QuestionId = 1,
                            Text = "3"
                        },
                        new
                        {
                            Id = 4,
                            IsRight = false,
                            QuestionId = 1,
                            Text = "4"
                        },
                        new
                        {
                            Id = 5,
                            IsRight = false,
                            QuestionId = 2,
                            Text = "1"
                        },
                        new
                        {
                            Id = 6,
                            IsRight = true,
                            QuestionId = 2,
                            Text = "2"
                        },
                        new
                        {
                            Id = 7,
                            IsRight = false,
                            QuestionId = 2,
                            Text = "3"
                        },
                        new
                        {
                            Id = 8,
                            IsRight = false,
                            QuestionId = 2,
                            Text = "4"
                        },
                        new
                        {
                            Id = 9,
                            IsRight = false,
                            QuestionId = 3,
                            Text = "1"
                        },
                        new
                        {
                            Id = 10,
                            IsRight = false,
                            QuestionId = 3,
                            Text = "2"
                        },
                        new
                        {
                            Id = 11,
                            IsRight = true,
                            QuestionId = 3,
                            Text = "3"
                        },
                        new
                        {
                            Id = 12,
                            IsRight = false,
                            QuestionId = 3,
                            Text = "4"
                        },
                        new
                        {
                            Id = 13,
                            IsRight = true,
                            QuestionId = 4,
                            Text = "1"
                        },
                        new
                        {
                            Id = 14,
                            IsRight = false,
                            QuestionId = 4,
                            Text = "2"
                        },
                        new
                        {
                            Id = 15,
                            IsRight = true,
                            QuestionId = 5,
                            Text = "1"
                        },
                        new
                        {
                            Id = 16,
                            IsRight = false,
                            QuestionId = 5,
                            Text = "2"
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TestId = 1,
                            Text = "Choose 1"
                        },
                        new
                        {
                            Id = 2,
                            TestId = 1,
                            Text = "Choose 2"
                        },
                        new
                        {
                            Id = 3,
                            TestId = 1,
                            Text = "Choose 3"
                        },
                        new
                        {
                            Id = 4,
                            TestId = 2,
                            Text = "Choose 1"
                        },
                        new
                        {
                            Id = 5,
                            TestId = 3,
                            Text = "Choose 1"
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.Relationships.UserTestResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("access_time");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit")
                        .HasColumnName("finished");

                    b.Property<DateTime?>("FinishedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_time");

                    b.Property<int>("Result")
                        .HasColumnType("int")
                        .HasColumnName("result");

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("rel_user_test_result");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessTime = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(5298),
                            Finished = false,
                            FinishedTime = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(5455),
                            Result = 5,
                            TestId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccessTime = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(6001),
                            Finished = false,
                            FinishedTime = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(6001),
                            Result = 5,
                            TestId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccessTime = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(6002),
                            Finished = false,
                            FinishedTime = new DateTime(2024, 5, 19, 19, 12, 11, 101, DateTimeKind.Utc).AddTicks(6003),
                            Result = 0,
                            TestId = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.TestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit")
                        .HasColumnName("is_free");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C# is a general purpose object-oriented programming language.",
                            IsFree = true,
                            Title = "C# Start"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Java is a strongly typed, object-oriented, general-purpose programming language developed by Sun Microsystems.",
                            IsFree = true,
                            Title = "Java Start"
                        },
                        new
                        {
                            Id = 3,
                            Description = "JavaScript is a multi-paradigm programming language.",
                            IsFree = true,
                            Title = "JavaScript Start"
                        },
                        new
                        {
                            Id = 4,
                            Description = "C++ is a compiled, statically typed general-purpose programming language.",
                            IsFree = false,
                            Title = "C++ Start"
                        });
                });

            modelBuilder.Entity("DAL.Models.Entities.User.UserSettingsEntity", b =>
                {
                    b.HasOne("DAL.Models.Entities.User.UserEntity", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("DAL.Models.Entities.User.UserSettingsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IKnowCoding.API.Models.DTO.MainPage.FeedbackEntity", b =>
                {
                    b.HasOne("DAL.Models.Entities.User.UserEntity", "User")
                        .WithOne("Feedback")
                        .HasForeignKey("IKnowCoding.API.Models.DTO.MainPage.FeedbackEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.AnswerVariantEntity", b =>
                {
                    b.HasOne("IKnowCoding.DAL.Models.Entities.QuestionEntity", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.QuestionEntity", b =>
                {
                    b.HasOne("IKnowCoding.DAL.Models.Entities.TestEntity", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.Relationships.UserTestResultEntity", b =>
                {
                    b.HasOne("IKnowCoding.DAL.Models.Entities.TestEntity", "Test")
                        .WithMany("TestResultEntities")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAL.Models.Entities.User.UserEntity", "User")
                        .WithMany("TestResultEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Entities.User.UserEntity", b =>
                {
                    b.Navigation("Feedback")
                        .IsRequired();

                    b.Navigation("TestResultEntities");

                    b.Navigation("UserSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.QuestionEntity", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.TestEntity", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestResultEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
