// <auto-generated />
using System;
using IKnowCoding.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(PlatformContext))]
    partial class PlatformContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Entities.User.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("UserSettingsId")
                        .HasColumnType("int")
                        .HasColumnName("user_settings_id");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "valik@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Valentyn",
                            LastName = "Riabinchak",
                            Password = "11111111",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "vasylyna@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Vasylyna",
                            LastName = "Leheta",
                            Password = "22222222",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "igor@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Igor",
                            LastName = "Zaitsev",
                            Password = "33333333",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "tom@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Tom",
                            LastName = "Bot",
                            Password = "44444444",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 5,
                            Email = "admin@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Mr. Admin",
                            LastName = "Secret Administator",
                            Password = "secretKey911#",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 6,
                            Email = "tom@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Tom",
                            LastName = "Bot",
                            Password = "55555555",
                            UserSettingsId = 0
                        },
                        new
                        {
                            Id = 7,
                            Email = "raf@gmail.com",
                            FeedbackId = 0,
                            FirstName = "Rafaella",
                            LastName = "Diniz",
                            Password = "rafaela12#",
                            UserSettingsId = 0
                        });
                });

            modelBuilder.Entity("DAL.Models.Entities.User.UserSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("access_token");

                    b.Property<DateTime?>("AccessTokenExpireTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("access_token_expire_time");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpireTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expire_time");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsAdmin = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsAdmin = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            IsAdmin = false,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("IKnowCoding.API.Models.DTO.MainPage.FeedbackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_path");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(2322),
                            ImagePath = "https://t3.ftcdn.net/jpg/02/99/04/20/360_F_299042079_vGBD7wIlSeNl7vOevWHiL93G4koMM967.jpg",
                            Text = "Досить корисний та захоплюючий сайт",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(2589),
                            ImagePath = "https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?q=80&w=2076&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Text = "Мені подобається випробовувати свої навички",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(2590),
                            ImagePath = "https://st2.depositphotos.com/2931363/6569/i/450/depositphotos_65699901-stock-photo-black-man-keeping-arms-crossed.jpg",
                            Text = "Хотілося б більше тестів",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(2590),
                            ImagePath = "https://images.unsplash.com/photo-1500048993953-d23a436266cf?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Text = "Покращує вміння мислити нестандартно та оцінити свої знання",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(2591),
                            ImagePath = "https://images.unsplash.com/photo-1504593811423-6dd665756598?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Text = "Подобається дизайн сайту, допомагає зосередитися",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(2591),
                            ImagePath = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Text = "Можна весело й корисно провести час",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(2592),
                            ImagePath = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D",
                            Text = "Гарний дизайн та хороша креативність",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.DTO.Main_Page.AchievementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_path");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(1395),
                            ImagePath = "https://startup-ukraine.foundation/wp-content/uploads/photo_5325816626395855791_y-1.jpg",
                            Source = "https://uk.wikipedia.org/wiki/%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%B8%D0%B9_%D1%84%D0%BE%D0%BD%D0%B4_%D1%81%D1%82%D0%B0%D1%80%D1%82%D0%B0%D0%BF%D1%96%D0%B2",
                            Text = "Загалом, до початку війни Фонд проінвестував понад 250 українських стартапів на суму більш як $6,4 млн. Було проведено 37 пітч-днів за участі 413 стартапів, а кількість поданих заявок на участь у грантових програмах Фонду перевищила 4,5 тис.",
                            Title = "Перше місце серед стартапів освітньої сфери"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(1675),
                            ImagePath = "https://marketer.ua/wp-content/uploads/2018/01/ua-it-ua.jpg",
                            Source = "https://marketer.ua/ua/top-10-achievements-of-ukrainians-in-the-world-it/",
                            Text = "Створено фонд, який за допомогою цього сайту організовує змагання на проходженні тестів.",
                            Title = "Найбільша кількість донатів на ЗСУ"
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.AnswerVariantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRight")
                        .HasColumnType("bit")
                        .HasColumnName("is_right");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsRight = false,
                            QuestionId = 1,
                            Text = "print (\"Hello World\");"
                        },
                        new
                        {
                            Id = 2,
                            IsRight = true,
                            QuestionId = 1,
                            Text = "Console.WriteLine(\"Hello World\");"
                        },
                        new
                        {
                            Id = 3,
                            IsRight = false,
                            QuestionId = 1,
                            Text = "cout << \"Hello World\";"
                        },
                        new
                        {
                            Id = 4,
                            IsRight = false,
                            QuestionId = 1,
                            Text = "System.out.println(\"Hello World\");"
                        },
                        new
                        {
                            Id = 5,
                            IsRight = true,
                            QuestionId = 2,
                            Text = "False"
                        },
                        new
                        {
                            Id = 6,
                            IsRight = false,
                            QuestionId = 2,
                            Text = "True"
                        },
                        new
                        {
                            Id = 7,
                            IsRight = false,
                            QuestionId = 3,
                            Text = "# This is a comment"
                        },
                        new
                        {
                            Id = 8,
                            IsRight = false,
                            QuestionId = 3,
                            Text = "/* This is a comment"
                        },
                        new
                        {
                            Id = 9,
                            IsRight = true,
                            QuestionId = 3,
                            Text = "// This is a comment"
                        },
                        new
                        {
                            Id = 10,
                            IsRight = false,
                            QuestionId = 4,
                            Text = "Txt"
                        },
                        new
                        {
                            Id = 11,
                            IsRight = false,
                            QuestionId = 4,
                            Text = "str"
                        },
                        new
                        {
                            Id = 12,
                            IsRight = false,
                            QuestionId = 4,
                            Text = "myString"
                        },
                        new
                        {
                            Id = 13,
                            IsRight = true,
                            QuestionId = 4,
                            Text = "string"
                        },
                        new
                        {
                            Id = 14,
                            IsRight = true,
                            QuestionId = 5,
                            Text = "int x = 5;"
                        },
                        new
                        {
                            Id = 15,
                            IsRight = false,
                            QuestionId = 5,
                            Text = "num x = 5"
                        },
                        new
                        {
                            Id = 16,
                            IsRight = false,
                            QuestionId = 5,
                            Text = "x = 5;"
                        },
                        new
                        {
                            Id = 17,
                            IsRight = false,
                            QuestionId = 3,
                            Text = "double x = 5;"
                        },
                        new
                        {
                            Id = 18,
                            IsRight = true,
                            QuestionId = 6,
                            Text = "double x = 2.8D;"
                        },
                        new
                        {
                            Id = 19,
                            IsRight = false,
                            QuestionId = 6,
                            Text = "byte x = 2.8"
                        },
                        new
                        {
                            Id = 20,
                            IsRight = false,
                            QuestionId = 6,
                            Text = "int x = 2.8;"
                        },
                        new
                        {
                            Id = 21,
                            IsRight = false,
                            QuestionId = 6,
                            Text = "int x = 2.8D;"
                        },
                        new
                        {
                            Id = 22,
                            IsRight = false,
                            QuestionId = 7,
                            Text = "<js>"
                        },
                        new
                        {
                            Id = 23,
                            IsRight = true,
                            QuestionId = 7,
                            Text = "<script>"
                        },
                        new
                        {
                            Id = 24,
                            IsRight = false,
                            QuestionId = 7,
                            Text = "<scripting>"
                        },
                        new
                        {
                            Id = 25,
                            IsRight = false,
                            QuestionId = 7,
                            Text = "<javascript>"
                        },
                        new
                        {
                            Id = 26,
                            IsRight = false,
                            QuestionId = 8,
                            Text = "The <body> section"
                        },
                        new
                        {
                            Id = 27,
                            IsRight = true,
                            QuestionId = 8,
                            Text = "Both the <head> section and the <body> section are correct"
                        },
                        new
                        {
                            Id = 28,
                            IsRight = false,
                            QuestionId = 8,
                            Text = "The <head> section"
                        },
                        new
                        {
                            Id = 29,
                            IsRight = true,
                            QuestionId = 9,
                            Text = "<script src=\"xxx.js\">"
                        },
                        new
                        {
                            Id = 30,
                            IsRight = false,
                            QuestionId = 9,
                            Text = "<script href=\"xxx.js\">"
                        },
                        new
                        {
                            Id = 31,
                            IsRight = false,
                            QuestionId = 9,
                            Text = "<script name=\"xxx.js\">"
                        },
                        new
                        {
                            Id = 32,
                            IsRight = false,
                            QuestionId = 10,
                            Text = "True"
                        },
                        new
                        {
                            Id = 33,
                            IsRight = true,
                            QuestionId = 10,
                            Text = "False"
                        },
                        new
                        {
                            Id = 34,
                            IsRight = false,
                            QuestionId = 11,
                            Text = "alertBox(\"Hello World\");"
                        },
                        new
                        {
                            Id = 35,
                            IsRight = false,
                            QuestionId = 11,
                            Text = "msgBox(\"Hello World\");"
                        },
                        new
                        {
                            Id = 36,
                            IsRight = false,
                            QuestionId = 11,
                            Text = "msg(\"Hello World\");"
                        },
                        new
                        {
                            Id = 37,
                            IsRight = true,
                            QuestionId = 11,
                            Text = "alert(\"Hello World\");"
                        },
                        new
                        {
                            Id = 38,
                            IsRight = false,
                            QuestionId = 12,
                            Text = "function = myFunction()"
                        },
                        new
                        {
                            Id = 39,
                            IsRight = false,
                            QuestionId = 12,
                            Text = "function:myFunction()"
                        },
                        new
                        {
                            Id = 40,
                            IsRight = true,
                            QuestionId = 12,
                            Text = "function myFunction()"
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TestId = 1,
                            Text = "What is a correct syntax to output \"Hello World\" in C#?"
                        },
                        new
                        {
                            Id = 2,
                            TestId = 1,
                            Text = "C# is an alias of C++"
                        },
                        new
                        {
                            Id = 3,
                            TestId = 1,
                            Text = "How do you insert COMMENTS in C# code?"
                        },
                        new
                        {
                            Id = 4,
                            TestId = 1,
                            Text = "Which data type is used to create a variable that should store text?"
                        },
                        new
                        {
                            Id = 5,
                            TestId = 1,
                            Text = "How do you create a variable with the numeric value 5?"
                        },
                        new
                        {
                            Id = 6,
                            TestId = 1,
                            Text = "How do you create a variable with the floating number 2.8?"
                        },
                        new
                        {
                            Id = 7,
                            TestId = 2,
                            Text = "Inside which HTML element do we put the JavaScript?"
                        },
                        new
                        {
                            Id = 8,
                            TestId = 2,
                            Text = "Where is the correct place to insert a JavaScript?"
                        },
                        new
                        {
                            Id = 9,
                            TestId = 2,
                            Text = "What is the correct syntax for referring to an external script called \"xxx.js\"?"
                        },
                        new
                        {
                            Id = 10,
                            TestId = 2,
                            Text = "The external JavaScript file must contain the <script> tag."
                        },
                        new
                        {
                            Id = 11,
                            TestId = 2,
                            Text = "How do you write \"Hello World\" in an alert box?"
                        },
                        new
                        {
                            Id = 12,
                            TestId = 2,
                            Text = "How do you create a function in JavaScript?"
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.Relationships.UserTestResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("access_time");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit")
                        .HasColumnName("finished");

                    b.Property<DateTime?>("FinishedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_time");

                    b.Property<int>("Result")
                        .HasColumnType("int")
                        .HasColumnName("result");

                    b.Property<int>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("test_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("rel_user_test_result");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessTime = new DateTime(2024, 5, 27, 8, 47, 40, 306, DateTimeKind.Utc).AddTicks(9899),
                            Finished = false,
                            FinishedTime = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(59),
                            Result = 6,
                            TestId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccessTime = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(478),
                            Finished = false,
                            FinishedTime = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(479),
                            Result = 4,
                            TestId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccessTime = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(480),
                            Finished = false,
                            FinishedTime = new DateTime(2024, 5, 27, 8, 47, 40, 307, DateTimeKind.Utc).AddTicks(480),
                            Result = 1,
                            TestId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.TestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit")
                        .HasColumnName("is_free");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C# is a general purpose object-oriented programming language.",
                            ImagePath = "https://miro.medium.com/v2/resize:fit:1400/1*_NVBTVdmjt3Qvq3CZOySXg.png",
                            IsFree = true,
                            Title = "C# Start"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Java is a strongly typed, object-oriented, general-purpose programming language developed by Sun Microsystems.",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/ru/thumb/3/39/Java_logo.svg/1200px-Java_logo.svg.png",
                            IsFree = true,
                            Title = "Java Start"
                        },
                        new
                        {
                            Id = 2,
                            Description = "JavaScript is a multi-paradigm programming language.",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/1200px-Unofficial_JavaScript_logo_2.svg.png",
                            IsFree = true,
                            Title = "JavaScript Start"
                        },
                        new
                        {
                            Id = 4,
                            Description = "C++ is a compiled, statically typed general-purpose programming language.",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1200px-ISO_C%2B%2B_Logo.svg.png",
                            IsFree = false,
                            Title = "C++ Start"
                        });
                });

            modelBuilder.Entity("DAL.Models.Entities.User.UserSettingsEntity", b =>
                {
                    b.HasOne("DAL.Models.Entities.User.UserEntity", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("DAL.Models.Entities.User.UserSettingsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IKnowCoding.API.Models.DTO.MainPage.FeedbackEntity", b =>
                {
                    b.HasOne("DAL.Models.Entities.User.UserEntity", "User")
                        .WithOne("Feedback")
                        .HasForeignKey("IKnowCoding.API.Models.DTO.MainPage.FeedbackEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.AnswerVariantEntity", b =>
                {
                    b.HasOne("IKnowCoding.DAL.Models.Entities.QuestionEntity", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.QuestionEntity", b =>
                {
                    b.HasOne("IKnowCoding.DAL.Models.Entities.TestEntity", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.Relationships.UserTestResultEntity", b =>
                {
                    b.HasOne("IKnowCoding.DAL.Models.Entities.TestEntity", "Test")
                        .WithMany("TestResultEntities")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAL.Models.Entities.User.UserEntity", "User")
                        .WithMany("TestResultEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Entities.User.UserEntity", b =>
                {
                    b.Navigation("Feedback")
                        .IsRequired();

                    b.Navigation("TestResultEntities");

                    b.Navigation("UserSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.QuestionEntity", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("IKnowCoding.DAL.Models.Entities.TestEntity", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestResultEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
